const codonTableForward = {
    "AAA": "Lys",
    "AAC": "Asn",
    "AAG": "Lys",
    "AAT": "Asn",
    "ACA": "Thr",
    "ACC": "Thr",
    "ACG": "Thr",
    "ACT": "Thr",
    "AGA": "Arg",
    "AGC": "Ser",
    "AGG": "Arg",
    "AGT": "Ser",
    "ATA": "Ile",
    "ATC": "Ile",
    "ATG": "Met",
    "ATT": "Ile",
    "CAA": "Gln",
    "CAC": "His",
    "CAG": "Gln",
    "CAT": "His",
    "CCA": "Pro",
    "CCC": "Pro",
    "CCG": "Pro",
    "CCT": "Pro",
    "CGA": "Arg",
    "CGC": "Arg",
    "CGG": "Arg",
    "CGT": "Arg",
    "CTA": "Leu",
    "CTC": "Leu",
    "CTG": "Leu",
    "CTT": "Leu",
    "GAA": "Glu",
    "GAC": "Asp",
    "GAG": "Glu",
    "GAT": "Asp",
    "GCA": "Ala",
    "GCC": "Ala",
    "GCG": "Ala",
    "GCT": "Ala",
    "GGA": "Gly",
    "GGC": "Gly",
    "GGG": "Gly",
    "GGT": "Gly",
    "GTA": "Val",
    "GTC": "Val",
    "GTG": "Val",
    "GTT": "Val",
    "TAA": "XXX",
    "TAC": "Tyr",
    "TAG": "XXX",
    "TAT": "Tyr",
    "TCA": "Ser",
    "TCC": "Ser",
    "TCG": "Ser",
    "TCT": "Ser",
    "TGA": "XXX",
    "TGC": "Cys",
    "TGG": "Trp",
    "TGT": "Cys",
    "TTA": "Leu",
    "TTC": "Phe",
    "TTG": "Leu",
    "TTT": "Phe"
};

const codonTableReverse = {
    "Lys": ["AAA", "AAG"],
    "Asn": ["AAC", "AAT"],
    "Thr": ["ACA", "ACC", "ACG", "ACT"],
    "Arg": ["AGA", "AGG", "CGA", "CGC", "CGG", "CGT"],
    "Ser": ["AGC", "AGT", "TCA", "TCC", "TCG", "TCT"],
    "Ile": ["ATA", "ATC", "ATT"],
    "Met": ["ATG"],
    "Gln": ["CAA", "CAG"],
    "His": ["CAC", "CAT"],
    "Pro": ["CCA", "CCC", "CCG", "CCT"],
    "Leu": ["CTA", "CTC", "CTG", "CTT", "TTA", "TTG"],
    "Glu": ["GAA", "GAG"],
    "Asp": ["GAC", "GAT"],
    "Ala": ["GCA", "GCC", "GCG", "GCT"],
    "Gly": ["GGA", "GGC", "GGG", "GGT"],
    "Val": ["GTA", "GTC", "GTG", "GTT"],
    "XXX": ["TAA", "TAG", "TGA"],
    "Tyr": ["TAC", "TAT"],
    "Cys": ["TGC", "TGT"],
    "Trp": ["TGG"],
    "Phe": ["TTC", "TTT"]
};
